# Version v1 Metadata
# Metadata for the initial migration to Option B package architecture

version: "v1"
created: "2025-01-11"
description: "Initial migration to Option B package architecture"
inputs:
  - OPERATING_PRINCIPLES
  - AGENT_CAPABILITIES
  - BASE_FORMATTING
  - CONVERSATIONAL_GUARDRAIL
  - system_blocks (optional)
  - AGENT_SKILLS (optional)
  - HR_KNOWLEDGE
  - AGENTS_AS_TOOLS (optional)
  - HANDOFFS (optional)
  - TOOL_CALLS (optional)
  - MCP_SERVERS (optional)
  - DYNAMIC_RUN_CONTEXT (optional)
  - INSTRUCTIONS_APPEND (optional)
dependencies:
  - messages.instructions.agents.variables.principles
  - messages.instructions.agents.variables.capabilities
  - messages.instructions.formatting
  - messages.instructions.guardrails